controller:
  replicaCount: 2
  config:
    # http-snippet : |
    #   limit_req_zone $binary_remote_addr zone=ingress_zone: 5m rate=100r/s;
    # location-snippet: |      
    #   limit_req zone=ingress_zone burst=20 nodelay;
    allow-snippet-annotations: "true"
    enable-vts-status: "false"
    limit-conn-status-code: "429"
    limit-req-status-code: "429"
    # use-proxy-protocol: "true" # Proxy protocol v2 for NLB must be enabled manually
    log-format-upstream: |
      [
      request_id: "$req_id"
      date: "$date_gmt"
      remote_addr: "$remote_addr"
      x-real-ip: "$realip_remote_addr"
      x_forwarded_for: "$proxy_add_x_forwarded_for"
      http_user_agent: "$http_user_agent"
      request: "$server_protocol $request_method $host$uri ? $args"
      status: "$status"
      upstream:
        upstream_name: "$proxy_upstream_name"
        upstream_addr: "$upstream_addr"
        upstream_status: "$upstream_status"
        upstream_response_time: "$upstream_response_time"
      bytes_sent: "$bytes_sent"
      body_bytes_sent: "$body_bytes_sent"
      request_time: "$request_time"
      request_length: "$request_length"
      request_body: "$request_body"
      ]

  resources:
    requests:
      cpu: "50m"
      memory: "192Mi"

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-subnets: ${balancer_subnets}
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    # spec:
    #   externalTrafficPolicy: "Cluster"

  metrics:
    enabled: true
