settings:
  clusterName: ${cluster_name}
  clusterEndpoint: ${cluster_endpoint}
  interruptionQueue: ${queue_name}

nodeSelector:
  karpenter.sh/controller: "true"
tolerations:
  - key: "karpenter.sh/controller"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

logLevel: "info"

serviceAccount:
  name: ${service_account}
  annotations:
    eks.amazonaws.com/role-arn: ${iam_role_arn}