---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  labels:
    CreatedBy: deployer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@email.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
