---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa # should be added 
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hv-secrets-test
  labels:
    app: hv-secrets-test
    namespace: default
spec:
  selector:
    matchLabels:
      app: hv-secrets-test
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true" # enable Vault-injector
        vault.hashicorp.com/agent-init-first: "true"
        
        vault.hashicorp.com/role: readonly-hv-role

        vault.hashicorp.com/agent-inject-secret-envs: /v1/kv/data/test/secrets # Path to secret in Vault
        vault.hashicorp.com/agent-inject-template-envs: |
          {{- with secret "kv/test/secrets" -}}
          {{- range $key, $value := .Data.data }}
          {{ $key | toUpper }}: {{ printf "'%s'" $value }}
          {{- end }}
          {{- end }}
      labels:
        app: hv-secrets-test
    spec:
      serviceAccountName: test-sa
      automountServiceAccountToken: true
      containers:
      - name: secret-reader
        image: alpine:latest # this is a public image
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            cat /vault/secrets/envs
            while true;do sleep 1;done
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
