---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hv-secrets-test
  labels:
    app: hv-secrets-test
spec:
  selector:
    matchLabels:
      app: hv-secrets-test
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-envs: /v1/apps/data/test/secret
        vault.hashicorp.com/agent-inject-template-envs: |
          {{- with secret "apps/data/test/secret" -}}
          {{- range $key, $value := .Data.data }}
          export {{ $key | toUpper }}={{ printf "'%s'" $value }}
          {{- end }}
          {{- end }}
        vault.hashicorp.com/role: readonly-hv-role
      labels:
        app: hv-secrets-test
    spec:
      serviceAccountName: test-sa
      automountServiceAccountToken: true
      containers:
      - name: secret-reader
        image: alpine:latest # this is a public image
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            echo "Checking for Vault secrets..."
            ls -la /vault/secrets/
            if [ -f /vault/secrets/envs ]; then
              echo "Found secrets file:"
              cat /vault/secrets/envs
            else
              echo "No secrets file found"
            fi
            while true; do sleep 30; done
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 50m
            memory: 256Mi
